<?= $this->extend('layouts/main') ?>

<?= $this->section('content') ?>
<div class="max-w-8xl mx-auto">
	<!-- Header -->
	<div class="mb-8">
	
		<p class="text-gray-600 mt-2">Control access levels and assign roles to your team</p>
	</div>

	<!-- Permission Matrix Tabs -->
	<div class="mb-6 border-b border-gray-200">
		<div class="flex space-x-8">
			<button class="tab-button active px-4 py-3 border-b-2 border-blue-600 text-blue-600 font-medium" data-tab="document">
				Document Management
			</button>
			<button class="tab-button px-4 py-3 border-b-2 border-transparent text-gray-600 hover:text-gray-900" data-tab="borrow">
				Borrow Management
			</button>
			<button class="tab-button px-4 py-3 border-b-2 border-transparent text-gray-600 hover:text-gray-900" data-tab="relocation">
				Relocation Management
			</button>
			<button class="tab-button px-4 py-3 border-b-2 border-transparent text-gray-600 hover:text-gray-900" data-tab="archive">
				Archive & Disposal
			</button>
			<button class="tab-button px-4 py-3 border-b-2 border-transparent text-gray-600 hover:text-gray-900" data-tab="system">
				System Admin
			</button>
		</div>
	</div>

	<!-- Permission Matrix Table -->
	<div id="matrixContainer" class="bg-white rounded-lg shadow overflow-hidden">
		<div class="overflow-x-auto">
			<table class="w-full border-collapse">
				<thead id="matrixHead">
					<!-- Headers will be generated by JavaScript -->
				</thead>
				<tbody id="matrixBody">
					<!-- Rows will be generated by JavaScript -->
				</tbody>
			</table>
		</div>
	</div>

	<!-- Save Button -->
	<div class="mt-6">
		<button id="saveBtn" class="px-8 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-semibold">
			Save Changes
		</button>
		<button id="resetBtn" class="ml-3 px-8 py-3 bg-gray-300 text-gray-900 rounded-lg hover:bg-gray-400 font-semibold">
			Reset
		</button>
	</div>
</div>

<script>
		const permissionGroups = {
			document: {
				name: 'Document Management',
				permissions: {
					'search_documents': 'Search & Find Documents',
					'view_shelf_map': 'View Shelf Map',
					'create_document_record': 'Create Document Records',
					'edit_document_metadata': 'Edit Document Metadata'
				}
			},
			borrow: {
				name: 'Borrow Management',
				permissions: {
					'request_borrow': 'Request to Borrow',
					'view_own_borrow': 'View Own Borrow Requests',
					'view_all_borrow': 'View All Borrow Requests',
					'process_borrow_release': 'Process Borrow Release',
					'process_return': 'Process Return',
					'approve_borrow_requests': 'Approve Requests',
					'view_alerts_module': 'View Alerts'
				}
			},
			relocation: {
				name: 'Relocation Management',
				permissions: {
					'initiate_relocation': 'Initiate Relocation',
					'request_relocation': 'Request Relocation',
					'approve_relocation': 'Approve Relocations'
				}
			},
			archive: {
				name: 'Archive & Disposal',
				permissions: {
					'archive_document': 'Archive Document',
					'view_archive_module': 'View Archive Module',
					'manage_archive_policies': 'Manage Policies',
					'view_disposal_workflow': 'View Disposal Workflow',
					'approve_disposal': 'Approve Disposal'
				}
			},
			system: {
				name: 'System Admin',
				permissions: {
					'manage_users': 'Manage Users',
					'manage_system_config': 'System Configuration',
					'view_audit_logs': 'View Audit Logs',
					'override_any_action': 'Override Actions'
				}
			}
		};

		const roles = <?= json_encode($roles) ?>;
		let currentTab = 'document';
		let matrixData = {};

		// Initialize matrix data structure
		function initializeMatrixData() {
			<?php foreach ($roles as $role): ?>
			matrixData[<?= $role['role_id'] ?>] = {};
			<?php endforeach; ?>
		}

		// Load role permissions from server
		function loadRolePermissions() {
			const promises = roles.map(role => {
				return $.ajax({
					url: `/admin/permissions/load-role/${role.role_id}`,
					type: 'GET',
					dataType: 'json',
					success: function(data) {
						if (data.error) {
							console.error(`Error loading role ${role.role_id}: ${data.error}`);
							matrixData[role.role_id] = {};
						} else {
							matrixData[role.role_id] = data || {};
							console.log(`Loaded permissions for role ${role.role_id}:`, matrixData[role.role_id]);
						}
					},
					error: function(xhr, status, error) {
						console.error(`Failed to load role ${role.role_id}: ${status} ${error}`, xhr.responseJSON);
						matrixData[role.role_id] = {};
					}
				});
			});

			// Wait for all AJAX calls to complete, then render
			$.when(...promises).done(function() {
				console.log('All permissions loaded, rendering matrix:', matrixData);
				renderMatrix(currentTab);
			});
		}

		// Render matrix table
		function renderMatrix(tab) {
			// Check if matrix needs initialization
			if ($('#matrixBody').find('tr').length === 0) {
				let headerHtml = '<tr class="bg-gray-50 border-b border-gray-200"><th class="px-6 py-4 text-left text-sm font-semibold text-gray-900 w-1/4">Role</th>';
				let bodyHtml = '';

				// Generate header columns for ALL tabs at once
				Object.entries(permissionGroups).forEach(([tabKey, tabGroup]) => {
					Object.entries(tabGroup.permissions).forEach(([key, label]) => {
						headerHtml += `<th class="px-6 py-4 text-center text-sm font-semibold text-gray-900" data-tab-group="${tabKey}" data-perm="${key}" style="display: ${tabKey === 'document' ? 'table-cell' : 'none'};">${label}</th>`;
					});
				});
				headerHtml += '</tr>';

				// Generate body rows for ALL permissions at once
				roles.forEach(role => {
					const isSuperAdmin = role.role_name === 'super_admin';
					bodyHtml += `<tr class="border-b border-gray-200 hover:bg-gray-50">
						<td class="px-6 py-4 font-medium text-gray-900">
							${role.role_name}
							${isSuperAdmin ? '<span class="text-xs bg-yellow-100 text-yellow-800 px-2 py-1 rounded ml-2">All Access</span>' : ''}
						</td>`;
					
					Object.entries(permissionGroups).forEach(([tabKey, tabGroup]) => {
						Object.entries(tabGroup.permissions).forEach(([key, label]) => {
							const isChecked = isSuperAdmin || (matrixData[role.role_id] && matrixData[role.role_id][key]);
							const disabledAttr = isSuperAdmin ? 'disabled' : '';
							const cursorClass = isSuperAdmin ? 'cursor-not-allowed opacity-60' : 'cursor-pointer';
							
							bodyHtml += `<td class="px-6 py-4 text-center tab-cell" data-tab-group="${tabKey}" style="display: ${tabKey === 'document' ? 'table-cell' : 'none'};">
								<input type="checkbox" class="perm-checkbox w-5 h-5 text-blue-600 rounded ${cursorClass}" 
									data-role="${role.role_id}" data-perm="${key}" ${isChecked ? 'checked' : ''} ${disabledAttr} 
									title="${isSuperAdmin ? 'Super admin has all permissions' : ''}">
							</td>`;
						});
					});
					
					bodyHtml += '</tr>';
				});

				$('#matrixHead').html(headerHtml);
				$('#matrixBody').html(bodyHtml);
			}

			// Show/hide columns based on selected tab
			$('#matrixHead th[data-tab-group], #matrixBody .tab-cell').hide();
			$('#matrixHead th:first-child').show(); // Always show role column
			$('#matrixHead th[data-tab-group="' + tab + '"]').show(); // Show only current tab headers
			$('#matrixBody .tab-cell[data-tab-group="' + tab + '"]').show(); // Show only current tab cells
		}

		// Handle tab switching
		$(document).on('click', '.tab-button', function() {
			$('.tab-button').removeClass('border-blue-600 text-blue-600').addClass('border-transparent text-gray-600');
			$(this).removeClass('border-transparent text-gray-600').addClass('border-blue-600 text-blue-600');
			currentTab = $(this).data('tab');
			renderMatrix(currentTab);
		});

		// Save changes
		$('#saveBtn').click(function() {
			const changes = {};
			
			// Get all roles from table
			const roles = <?= json_encode(array_column($roles, 'role_id')) ?>;
			const superAdminCheck = <?= json_encode(array_column($roles, 'role_id', 'role_name')) ?>;
			
			// Collect checked permissions for each role (skip super_admin)
			roles.forEach(roleId => {
				// Skip super_admin role
				const isSuperAdmin = Object.keys(superAdminCheck).some(name => name === 'super_admin' && superAdminCheck[name] === roleId);
				if (!isSuperAdmin) {
					changes[roleId] = [];
				}
			});
			
			// Get all checked permissions (exclude super_admin)
			$('.perm-checkbox:checked').each(function() {
				const roleId = $(this).data('role');
				const perm = $(this).data('perm');
				// Only collect from non-super_admin roles
				if (changes.hasOwnProperty(roleId)) {
					changes[roleId].push(perm);
				}
			});

			console.log('Sending save request with data:', changes);

			if (confirm('Save permission changes?')) {
				$.ajax({
					url: '/admin/permissions/save-role-perms',
					type: 'POST',
					data: JSON.stringify(changes),
					contentType: 'application/json',
					dataType: 'json',
					statusCode: {
						400: function(xhr) {
							console.error('Bad request (400):', xhr.responseJSON);
							alert('Error: ' + (xhr.responseJSON?.error || 'Invalid data'));
						},
						403: function(xhr) {
							console.error('Forbidden (403):', xhr.responseJSON);
							alert('Error: You do not have permission to manage users');
						},
						500: function(xhr) {
							console.error('Server error (500):', xhr.responseJSON);
							alert('Error: ' + (xhr.responseJSON?.error || 'Server error'));
						}
					},
					success: function(response) {
						console.log('Response received:', response);
						
						if (response.success) {
							alert('Permissions saved successfully!');
							// Wait 500ms for database to fully commit before reloading
							setTimeout(() => {
								console.log('Refreshing role permissions...');
								matrixData = {}; // Reset cache
								initializeMatrixData();
								loadRolePermissions(); // This will render the matrix once all data is loaded
							}, 500);
						} else {
							alert('Error: ' + (response.error || 'Failed to save permissions'));
						}
					},
					error: function(xhr, status, error) {
						console.error('AJAX error - status:', xhr.status, 'error:', error);
						console.error('Response:', xhr.responseJSON || xhr.responseText);
						
						// If statusCode handlers didn't catch it
						if (!xhr.responseJSON || !xhr.responseJSON.error) {
							alert('Error: ' + (error || 'Failed to save permissions'));
						}
					}
				});
			}
		});

		// Reset
		$('#resetBtn').click(function() {
			matrixData = {}; // Clear cache
			initializeMatrixData();
			loadRolePermissions(); // This now waits for all data before rendering
		});

		// Initialize on page load
		$(document).ready(function() {
			console.log('Initializing permission matrix...');
			initializeMatrixData();
			loadRolePermissions(); // This will render the matrix once all data is loaded
		});
	</script>
<?= $this->endSection() ?>
