<?= $this->extend('layouts/main') ?>

<?= $this->section('content') ?>
<div class="max-w-7xl mx-auto">
	<!-- Header -->
	<div class="mb-8">
		<h1 class="text-4xl font-bold text-gray-900">Team & Permissions</h1>
		<p class="text-gray-600 mt-2">Control access levels and assign roles to your team</p>
	</div>

	<!-- Permission Matrix Tabs -->
	<div class="mb-6 border-b border-gray-200">
		<div class="flex space-x-8">
			<button class="tab-button active px-4 py-3 border-b-2 border-blue-600 text-blue-600 font-medium" data-tab="document">
				Document Management
			</button>
			<button class="tab-button px-4 py-3 border-b-2 border-transparent text-gray-600 hover:text-gray-900" data-tab="borrow">
				Borrow Management
			</button>
			<button class="tab-button px-4 py-3 border-b-2 border-transparent text-gray-600 hover:text-gray-900" data-tab="relocation">
				Relocation Management
			</button>
			<button class="tab-button px-4 py-3 border-b-2 border-transparent text-gray-600 hover:text-gray-900" data-tab="archive">
				Archive & Disposal
			</button>
			<button class="tab-button px-4 py-3 border-b-2 border-transparent text-gray-600 hover:text-gray-900" data-tab="system">
				System Admin
			</button>
		</div>
	</div>

	<!-- Permission Matrix Table -->
	<div id="matrixContainer" class="bg-white rounded-lg shadow overflow-hidden">
		<div class="overflow-x-auto">
			<table class="w-full border-collapse">
				<thead id="matrixHead">
					<!-- Headers will be generated by JavaScript -->
				</thead>
				<tbody id="matrixBody">
					<!-- Rows will be generated by JavaScript -->
				</tbody>
			</table>
		</div>
	</div>

	<!-- Save Button -->
	<div class="mt-6">
		<button id="saveBtn" class="px-8 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-semibold">
			Save Changes
		</button>
		<button id="resetBtn" class="ml-3 px-8 py-3 bg-gray-300 text-gray-900 rounded-lg hover:bg-gray-400 font-semibold">
			Reset
		</button>
	</div>
</div>

<script>
		const permissionGroups = {
			document: {
				name: 'Document Management',
				permissions: {
					'search_documents': 'Search & Find Documents',
					'view_shelf_map': 'View Shelf Map',
					'create_document_record': 'Create Document Records',
					'edit_document_metadata': 'Edit Document Metadata'
				}
			},
			borrow: {
				name: 'Borrow Management',
				permissions: {
					'request_borrow': 'Request to Borrow',
					'process_borrow_release': 'Process Borrow Release',
					'process_return': 'Process Return',
					'approve_borrow_requests': 'Approve Requests',
					'view_alerts_module': 'View Alerts'
				}
			},
			relocation: {
				name: 'Relocation Management',
				permissions: {
					'request_relocation': 'Request Relocation',
					'approve_relocations': 'Approve Relocations'
				}
			},
			archive: {
				name: 'Archive & Disposal',
				permissions: {
					'archive_document': 'Archive Document',
					'view_archive_module': 'View Archive Module',
					'manage_archive_policies': 'Manage Policies',
					'view_disposal_workflow': 'View Disposal Workflow',
					'approve_disposal': 'Approve Disposal'
				}
			},
			system: {
				name: 'System Admin',
				permissions: {
					'manage_users': 'Manage Users',
					'manage_system_config': 'System Configuration',
					'view_audit_logs': 'View Audit Logs',
					'override_any_action': 'Override Actions'
				}
			}
		};

		const roles = <?= json_encode($roles) ?>;
		let currentTab = 'document';
		let matrixData = {};

		// Track checked permissions across all tabs (not just current tab)
		let allCheckedPermissions = {};

		// Initialize matrix data structure
		function initializeMatrixData() {
			<?php foreach ($roles as $role): ?>
			matrixData[<?= $role['role_id'] ?>] = {};
			<?php endforeach; ?>
			// Reset all checked permissions when re-initializing
			allCheckedPermissions = {};
		}

		// Load role permissions from server
		function loadRolePermissions() {
			const promises = roles.map(role => {
				return $.ajax({
					url: `/admin/permissions/load-role/${role.role_id}`,
					type: 'GET',
					dataType: 'json',
					success: function(data) {
						if (data.error) {
							console.error(`Error loading role ${role.role_id}: ${data.error}`);
							matrixData[role.role_id] = {};
						} else {
							matrixData[role.role_id] = data || {};
							console.log(`Loaded permissions for role ${role.role_id}:`, matrixData[role.role_id]);
						}
					},
					error: function(xhr, status, error) {
						console.error(`Failed to load role ${role.role_id}: ${status} ${error}`, xhr.responseJSON);
						matrixData[role.role_id] = {};
					}
				});
			});

			// Wait for all AJAX calls to complete, then initialize and render
			$.when(...promises).done(function() {
				console.log('All permissions loaded, initializing tracker:', matrixData);
				initializeAllCheckedPermissions(); // Initialize allCheckedPermissions from server data
				renderMatrix(currentTab);
			});
		}

		// Render matrix table
		function renderMatrix(tab) {
			const group = permissionGroups[tab];
			const perms = Object.entries(group.permissions);
			let headerHtml = '<tr class="bg-gray-50 border-b border-gray-200"><th class="px-6 py-4 text-left text-sm font-semibold text-gray-900 w-1/4">Role</th>';
			let bodyHtml = '';

			// Generate header columns
			perms.forEach(([key, label]) => {
				headerHtml += `<th class="px-6 py-4 text-center text-sm font-semibold text-gray-900">${label}</th>`;
			});
			headerHtml += '</tr>';

			// Generate body rows
			roles.forEach(role => {
				const isSuperAdmin = role.role_name === 'super_admin';
				bodyHtml += `<tr class="border-b border-gray-200 hover:bg-gray-50">
					<td class="px-6 py-4 font-medium text-gray-900">
						${role.role_name}
						${isSuperAdmin ? '<span class="text-xs bg-yellow-100 text-yellow-800 px-2 py-1 rounded ml-2">All Access</span>' : ''}
					</td>`;
				
				perms.forEach(([key, label]) => {
					// Check both allCheckedPermissions (user changes) AND matrixData (server state)
					// Use allCheckedPermissions if it exists, otherwise fall back to matrixData
					const userChecked = allCheckedPermissions[role.role_id] && allCheckedPermissions[role.role_id][key];
					const serverChecked = matrixData[role.role_id] && matrixData[role.role_id][key];
					const isChecked = isSuperAdmin || userChecked || serverChecked;
					const disabledAttr = isSuperAdmin ? 'disabled' : '';
					const cursorClass = isSuperAdmin ? 'cursor-not-allowed opacity-60' : 'cursor-pointer';
					
					bodyHtml += `<td class="px-6 py-4 text-center">
						<input type="checkbox" class="perm-checkbox w-5 h-5 text-blue-600 rounded ${cursorClass}" 
							data-role="${role.role_id}" data-perm="${key}" ${isChecked ? 'checked' : ''} ${disabledAttr} 
							title="${isSuperAdmin ? 'Super admin has all permissions' : ''}">
					</td>`;
				});
				
				bodyHtml += '</tr>';
			});

			$('#matrixHead').html(headerHtml);
			$('#matrixBody').html(bodyHtml);
		}

		// Initialize allCheckedPermissions from loaded matrixData (only once after loading)
		function initializeAllCheckedPermissions() {
			allCheckedPermissions = {};
			roles.forEach(role => {
				if (!allCheckedPermissions[role.role_id]) {
					allCheckedPermissions[role.role_id] = {};
				}
				// Get all permissions for all groups
				Object.keys(permissionGroups).forEach(groupKey => {
					const groupPerms = Object.keys(permissionGroups[groupKey].permissions);
					groupPerms.forEach(perm => {
						const isChecked = matrixData[role.role_id] && matrixData[role.role_id][perm];
						if (isChecked) {
							allCheckedPermissions[role.role_id][perm] = true;
						}
					});
				});
			});
			console.log('Initialized allCheckedPermissions from server data:', allCheckedPermissions);
		}

		// Handle checkbox changes
		$(document).on('change', '.perm-checkbox', function() {
			const roleId = $(this).data('role');
			const perm = $(this).data('perm');
			
			if (!allCheckedPermissions[roleId]) {
				allCheckedPermissions[roleId] = {};
			}
			
			if ($(this).is(':checked')) {
				allCheckedPermissions[roleId][perm] = true;
			} else {
				delete allCheckedPermissions[roleId][perm];
			}
			
			// Also sync back to matrixData
			matrixData[roleId][perm] = $(this).is(':checked');
		});

		// Handle tab switching
		$(document).on('click', '.tab-button', function() {
			$('.tab-button').removeClass('border-blue-600 text-blue-600').addClass('border-transparent text-gray-600');
			$(this).removeClass('border-transparent text-gray-600').addClass('border-blue-600 text-blue-600');
			currentTab = $(this).data('tab');
			renderMatrix(currentTab);
		});

		// Save changes
		$('#saveBtn').click(function() {
			// Build changes from allCheckedPermissions (not just current DOM)
			const changes = {};
			
			// Process each role
			roles.forEach(role => {
				const roleId = role.role_id;
				// Skip super_admin role
				if (role.role_name !== 'super_admin') {
					// Convert object keys to array and send all permissions for this role
					if (allCheckedPermissions[roleId]) {
						changes[roleId] = Object.keys(allCheckedPermissions[roleId]);
					} else {
						changes[roleId] = [];
					}
				}
			});

			if (confirm('Save permission changes?')) {
				$.ajax({
					url: '/admin/permissions/save-role-perms',
					type: 'POST',
					data: JSON.stringify(changes),
					contentType: 'application/json',
					dataType: 'json',
					statusCode: {
						400: function(xhr) {
							console.error('Bad request (400):', xhr.responseJSON);
							alert('Error: ' + (xhr.responseJSON?.error || 'Invalid data'));
						},
						403: function(xhr) {
							console.error('Forbidden (403):', xhr.responseJSON);
							alert('Error: You do not have permission to manage users');
						},
						500: function(xhr) {
							console.error('Server error (500):', xhr.responseJSON);
							alert('Error: ' + (xhr.responseJSON?.error || 'Server error'));
						}
					},
					success: function(response) {
						console.log('Response received:', response);
						
						if (response.success) {
							alert('Permissions saved successfully!');
							// Wait 500ms for database to fully commit before reloading
							setTimeout(() => {
								console.log('Refreshing role permissions...');
								matrixData = {}; // Reset cache
								initializeMatrixData();
								loadRolePermissions(); // This will render the matrix once all data is loaded
							}, 500);
						} else {
							alert('Error: ' + (response.error || 'Failed to save permissions'));
						}
					},
					error: function(xhr, status, error) {
						console.error('AJAX error - status:', xhr.status, 'error:', error);
						console.error('Response:', xhr.responseJSON || xhr.responseText);
						
						// If statusCode handlers didn't catch it
						if (!xhr.responseJSON || !xhr.responseJSON.error) {
							alert('Error: ' + (error || 'Failed to save permissions'));
						}
					}
				});
			}
		});

		// Reset
		$('#resetBtn').click(function() {
			matrixData = {}; // Clear cache
			allCheckedPermissions = {}; // Clear user changes
			initializeMatrixData();
			loadRolePermissions(); // This now waits for all data before rendering
		});

		// Initialize on page load
		$(document).ready(function() {
			console.log('Initializing permission matrix...');
			initializeMatrixData();
			loadRolePermissions(); // This will render the matrix once all data is loaded
		});
	</script>
<?= $this->endSection() ?>
